Controllers/GerenciamentoController.cs
using Microsoft.AspNetCore.Mvc;
using processo_estágio.BancoDeDados.Entrada;
using processo_estágio.BancoDeDados.Mercadorias;
using processo_estágio.BancoDeDados.QuantidadeTotal;
using processo_estágio.BancoDeDados.Saida;
using processo_estágio.Models;
using System.Data;

namespace processo_estágio.Controllers
{
    public class GerenciamentoController : Controller
    {
        public IActionResult Index()
        {

            GetDataModel.MercadoriasEntradaHistorico = null;
            GetDataModel.MercadoriasSaidaHistorico = null;

            return View();
        }

        public IActionResult Entrada()
        {

            GetDataModel model = new GetDataModel();

            model.MercadoriasModel = DatabaseMercadorias.ObterDados();

            return View(model);
        }

        public IActionResult Saida()
        {
            GetDataModel model = new GetDataModel();

            model.MercadoriasModel = DatabaseMercadorias.ObterDados();

            return View(model);
        }

        // ACTION CHAMANDO MÉTODO DO BANCO DE DADOS DA MERCADORIA PARA INSERIR DADOS NA TABELA
        public ActionResult Adicionar(string nome, string fabricante, string tipo, string descricao)
        {

            if (nome != null && fabricante != null && tipo != null && descricao != null)
            {
                DatabaseMercadorias.InserirDados(nome, fabricante, tipo, descricao);
                DatabaseQuantidadeTotal.InserirDados(nome);
            }

            return RedirectToAction("Index");
        }

        // ACTION CHAMANDO MÉTODO DO BANCO DE DADOS DA ENTRADA PARA INSERIR DADOS NA TABELA
        public ActionResult Entrar(string quantidade, string dia, string mes, string ano, string hora, string local, string mercadoria)
        {

            DataTable QntdAtual = DatabaseQuantidadeTotal.ObterQuantidadeAtual(mercadoria);

            int valorAtual = Convert.ToInt32(QntdAtual.Rows[0].ItemArray[0]);

            int novoValor = valorAtual + int.Parse(quantidade);

            if (quantidade != null && dia != null && mes != null && ano != null && hora != null && local != null && mercadoria != null)
            {
                DatabaseEntrada.InserirDados(quantidade, dia, mes, ano, hora, local, mercadoria);
                DatabaseQuantidadeTotal.AtualizarQuantidade(novoValor, mercadoria);
            }


            return RedirectToAction("Index");
        }

        // ACTION CHAMANDO MÉTODO DO BANCO DE DADOS DA SAIDA PARA INSERIR DADOS NA TABELA
        public ActionResult Sair(string quantidade, string dia, string mes, string ano, string hora, string local, string mercadoria)
        {

            DataTable dados = DatabaseQuantidadeTotal.ObterQuantidadeAtual(mercadoria);

            int quantidadeTotal = Convert.ToInt32(dados.Rows[0].ItemArray[0]);

            int novoValor = quantidadeTotal - int.Parse(quantidade);

            if (Convert.ToInt32(quantidade) <= quantidadeTotal && Convert.ToInt32(quantidade) >= 0)
            {
                if (quantidade != null && dia != null && mes != null && ano != null && hora != null && local != null && mercadoria != null)
                {
                    DatabaseSaida.InserirDados(quantidade, dia, mes, ano, hora, local, mercadoria);
                    DatabaseQuantidadeTotal.AtualizarQuantidade(novoValor,mercadoria);
                }

                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Informe");
            }
        }

        public ActionResult Informe()
        {
            return View();
        }
    }
}

Views/Gerenciamento/Entrada.cshtml
@using System.Data;
@model GetDataModel
@{
	ViewData["Title"] = "Entrada de produtos";
}

@if (Model.MercadoriasModel?.Rows.Count == 0 || Model.MercadoriasModel?.Rows == null)
{
	<h2 class="text-center text-secondary mt-5">Sem mercadorias cadastradas no momentos.</h2>
}
else
{

	<form id="form-entrada" class="w-25" method="post" action="Entrar">
		<div class="form-group">
			<label for="quantidade">Quantidade</label>
			<input type="number" class="form-control" name="quantidade" id="quantidade-ent" placeholder="Quantidades de produto">
		</div>
		<div class="w-100 d-flex">
			<div>
				<label for="dia">Dia</label>
				<input type="number" class="form-control" name="dia" id="dia-ent" placeholder="Dia">
			</div>
			<div class="form-group">
				<label for="mes">Mês</label>
				<input type="number" class="form-control" name="mes" id="mes-ent" placeholder="01,02,03">
			</div>
			<div class="form-group">
				<label for="ano">Ano</label>
				<input type="number" class="form-control" name="ano" id="ano-ent" placeholder="Ano">
			</div>
		</div>

		<div class="form-group">
			<label for="hora">Hora</label>
			<input type="text" class="form-control" name="hora" id="hora-ent" placeholder="HH:MM">
		</div>
		<div class="form-group">
			<label for="local">Local</label>
			<input type="text" class="form-control" name="local" id="local-ent" placeholder="Local">
		</div>
		<div class="form-group">
			<label for="select">Selecione o produto</label>
			<select name="mercadoria" id="select" class="form-select">
				@foreach (DataRow row in Model.MercadoriasModel.Rows)
				{
					<option value=@row["NOME"]>@row["NOME"]</option>
				}
			</select>
		</div>

		<button id="btn-entrar-produto" type="submit" class="btn btn-primary mt-1">Entrar produto</button>
	</form>
}

Views/Gerenciamento/Index.cshtml
@{
    ViewData["Title"] = "Gerenciar produtos";
}

<h1 class="display-5 text-secondary mb-5">Adicionar mercadoria</h1>

<form id="form-cadastro" class="w-25" method="post" action="Gerenciamento/Adicionar">
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" class="form-control" name="nome" id="nome" placeholder="Nome do produto">
    </div>
    <div class="form-group">
        <label for="fabricante">Fabricante</label>
        <input type="text" class="form-control" name="fabricante" id="fabricante" placeholder="Nome do fabricante">
    </div>
    <div class="form-group">
        <label for="tipo">Tipo</label>
        <input type="text" class="form-control" name="tipo" id="tipo" placeholder="Tipo do produto">
    </div>
    <div class="form-group">
        <label for="descricao">Descrição</label>
        <textarea type="text" class="form-control" name="descricao" id="descricao" placeholder="Descrição do produto"></textarea>
    </div>
    <button type="submit" class="btn btn-primary mt-1">Cadastrar</button>
</form>

<div class="mt-4">
    <a class="btn btn-secondary" asp-controller="Gerenciamento" asp-action="Entrada">Entrada de produtos</a>
    <a class="btn btn-secondary" asp-controller="Gerenciamento" asp-action="Saida">Saída de produtos</a>
</div>

Views/Gerenciamento/Informe.cshtml
@{
    ViewData["Title"] = "Atenção";
}

<h3 class="text-danger">Ação inválida, quantidade de produtos para retirada é maior que a do estoque!</h3>

<form action="Entrada">
    <button class="btn btn-outline-danger w-25 mt-1">Voltar</button>
</form>

Views/Gerenciamento/Saida.cshtml
@using System.Data;
@model GetDataModel
@{
	ViewData["Title"] = "Saída de produtos";
}

@if (Model.MercadoriasModel?.Rows.Count == 0 || Model.MercadoriasModel?.Rows == null)
{
	<h2 class="text-center text-secondary mt-5">Sem mercadorias cadastradas no momentos.</h2>
}
else
{
	<form id="form-saida" class="w-25" method="post" action="Sair">
		<div class="form-group">
			<label for="quantidade">Quantidade</label>
			<input type="number" class="form-control" name="quantidade" id="quantidade-saida" placeholder="Quantidades de produto">
		</div>
		<div class="w-100 d-flex">
			<div>
				<label for="dia">Dia</label>
				<input type="number" class="form-control" name="dia" id="dia-saida" placeholder="Dia">
			</div>
			<div class="form-group">
				<label for="mes">Mês</label>
				<input type="number" class="form-control" name="mes" id="mes-saida" placeholder="01,02,03">
			</div>
			<div class="form-group">
				<label for="ano">Ano</label>
				<input type="number" class="form-control" name="ano" id="ano-saida" placeholder="Ano">
			</div>
		</div>
		<div class="form-group">
			<label for="hora">Hora</label>
			<input type="text" class="form-control" name="hora" id="hora-saida" placeholder="HH:MM">
		</div>
		<div class="form-group">
			<label for="local">Local</label>
			<input type="text" class="form-control" name="local" id="local-saida" placeholder="Local">
		</div>
		<div class="form-group">
			<label for="select">Selecione o produto</label>
			<select name="mercadoria" id="select" class="form-select">
				@foreach (DataRow row in Model.MercadoriasModel.Rows)
				{
					<option value=@row["NOME"]>@row["NOME"]</option>
				}
			</select>
		</div>
		<button type="submit" class="btn btn-primary mt-1">Retirar produto</button>
	</form>
}