Controllers/HistoricoController.cs
using Microsoft.AspNetCore.Mvc;
using processo_estágio.BancoDeDados.Entrada;
using processo_estágio.BancoDeDados.Mercadorias;
using processo_estágio.BancoDeDados.Saida;
using processo_estágio.Models;
using System.Data;
using iTextSharp.text.pdf;
using iTextSharp.text;
using processo_estágio.BancoDeDados.QuantidadeTotal;

namespace processo_estágio.Controllers
{
	public class HistoricoController : Controller
	{
		public IActionResult Index()
		{

			GetDataModel model = new()
			{
				MercadoriasModel = DatabaseMercadorias.ObterDados()
			};

			return View(model);
		}

		// CHAMA UM MÉTODO DO BANCO DE DADOS DA ENTRADA PARA OBTER OS DADOS DE UM DETERMINADA MERCADORIA
		public ActionResult ObterDadosEntrada(string mercadoria)
		{

			DataTable DadosEntrada = DatabaseEntrada.ObterDadosHistorico(mercadoria);


			GetDataModel.MercadoriasEntradaHistorico = DadosEntrada;

			return RedirectToAction("Index");

		}

		// CHAMA UM MÉTODO DO BANCO DE DADOS DA SAIDA PARA OBTER OS DADOS DE UM DETERMINADA MERCADORIA
		public ActionResult ObterDadosSaidaSegundo(string mercadoria)
		{

			DataTable DadosSaida = DatabaseSaida.ObterDadosHistorico(mercadoria);

			GetDataModel.MercadoriasSaidaHistorico = DadosSaida;

			return RedirectToAction("Index");

		}

		//CHAMA A VIEW DE CONFIRMAÇÃO DE EXCLUSÃO DA ENTRADA, PASSANDO O ID
		public ActionResult HistoricoConfirmarExc(string id, string nome)
		{

			GetDataModel.idDeletarHistorico = id;
			GetDataModel.nomeMercadoriaEntDeletada = nome;
			return View();
		}

		// CHAMA MÉTODO PARA EXCLUSÃO DE REGISTRO DE UM ITEM DO BANCO DE DADOS DA ENTRADA
		public ActionResult ExcHistoricoEnt()
		{
			DatabaseEntrada.DeletarHistoricoEntrada(GetDataModel.idDeletarHistorico);

			DataTable QntdEntrada = DatabaseEntrada.ObterQuantidadeEnt(GetDataModel.nomeMercadoriaEntDeletada);

			int QuantidadeTotalAtualizada = 0;

			for (int i = 0; i < QntdEntrada.Rows.Count; i++)
			{
				QuantidadeTotalAtualizada += Convert.ToInt32(QntdEntrada.Rows[i].ItemArray[0]);
			}

			DatabaseQuantidadeTotal.AtualizarQuantidade(QuantidadeTotalAtualizada, GetDataModel.nomeMercadoriaEntDeletada);

			GetDataModel.MercadoriasEntradaHistorico = null;
			GetDataModel.MercadoriasSaidaHistorico = null;

			return RedirectToAction("Index");
		}

		//CHAMA A VIEW DE CONFIRMAÇÃO DE EXCLUSÃO DA SAIDA, PASSANDO O ID
		public ActionResult ConfirmarExcSaida(string id, string quantidade, string nome)
		{
			GetDataModel.idDeletarHistorico = id;
			GetDataModel.qntMercadoriaSaidaDeletada = quantidade;
			GetDataModel.nomeMercadoriaSaidaDeletada = nome;
			return View();
		}

		// CHAMA MÉTODO PARA EXCLUSÃO DE REGISTRO DE UM ITEM DO BANCO DE DADOS DA SAIDA
		public ActionResult HistoricoSaidaExc()
		{


			DataTable QntdAtual = DatabaseQuantidadeTotal.ObterQuantidadeAtual(GetDataModel.nomeMercadoriaSaidaDeletada);

			int novoValor = Convert.ToInt32(QntdAtual.Rows[0].ItemArray[0]) + Convert.ToInt32(GetDataModel.qntMercadoriaSaidaDeletada);

			DatabaseQuantidadeTotal.AtualizarQuantidade(novoValor, GetDataModel.nomeMercadoriaSaidaDeletada);
			DatabaseSaida.DeletarHistoricoSaida(GetDataModel.idDeletarHistorico);
			GetDataModel.MercadoriasEntradaHistorico = null;
			GetDataModel.MercadoriasSaidaHistorico = null;
			return RedirectToAction("Index");
		}

		// CHAMA O FORMULÁRIO DE EDIÇÃO DA ENTRADA
		public ActionResult AttHistoricoEntrada(int id, string nome)
		{

			GetDataModel.idAtualizarHistorico = id;
			GetDataModel.nomeMercadoriaEntradaAtualizar = nome;

			GetDataModel.DadosHistoricoEntAtt = DatabaseEntrada.ObterDadosParaAtualizar(id);

			return View();
		}

		// ATUALIZA O REGISTRO DE ENTRADA + LÓGICA PARA ATUALIZAR TAMBÉM A QUANTIDADE TOTAL
		public ActionResult AtualizarHistoricoEnt(int quantidade, int dia, int mes, int ano, string hora, string local)
		{
			DataTable QntdEntAntiga = DatabaseEntrada.ObterQuantidadeEntEspecifica(GetDataModel.idAtualizarHistorico);

			DataTable QntdTotalAtual = DatabaseQuantidadeTotal.ObterQuantidadeAtual(GetDataModel.nomeMercadoriaEntradaAtualizar);

			if (Convert.ToInt32(QntdEntAntiga.Rows[0].ItemArray[0]) < quantidade)
			{
				int ValorDiferenca = quantidade - Convert.ToInt32(QntdEntAntiga.Rows[0].ItemArray[0]);
				int novoValor = Convert.ToInt32(QntdTotalAtual.Rows[0].ItemArray[0]) + ValorDiferenca;
				DatabaseQuantidadeTotal.AtualizarQuantidade(novoValor, GetDataModel.nomeMercadoriaEntradaAtualizar);
			} else if(Convert.ToInt32(QntdEntAntiga.Rows[0].ItemArray[0]) > quantidade)
			{
				int ValorDiferenca = Convert.ToInt32(QntdEntAntiga.Rows[0].ItemArray[0]) - quantidade;
				int novoValor = Convert.ToInt32(QntdTotalAtual.Rows[0].ItemArray[0]) - ValorDiferenca;
				DatabaseQuantidadeTotal.AtualizarQuantidade(novoValor, GetDataModel.nomeMercadoriaEntradaAtualizar);
			}


			DatabaseEntrada.AtualizarHistoricoEnt(GetDataModel.idAtualizarHistorico, quantidade, dia, mes, ano, hora, local);
			GetDataModel.MercadoriasEntradaHistorico = null;
			GetDataModel.MercadoriasSaidaHistorico = null;

			return RedirectToAction("Index");
		}

		// CHAMA O FORMULÁRIO DE EDIÇÃO DA SAIDA
		public ActionResult AttHistoricoSaida(int id,string nome)
		{
			GetDataModel.idAtualizarHistorico = id;
			GetDataModel.nomeMercadoriaSaidaAtualizar = nome;

			GetDataModel.DadosHistoricoSaidaAtt = DatabaseSaida.ObterDadosParaAtualizar(id);

			return View();
		}

		// ATUALIZA O REGISTRO DE SAIDA + LÓGICA PARA ATUALIZAR TAMBÉM A QUANTIDADE TOTAL
		public ActionResult AtualizarHistoricoSaida(int quantidade, int dia, int mes, int ano, string hora, string local)
		{

			DataTable QntdSaidaAntiga = DatabaseSaida.ObterQuantidadeEntEspecifica(GetDataModel.idAtualizarHistorico);
			DataTable QntdTotalAtual = DatabaseQuantidadeTotal.ObterQuantidadeAtual(GetDataModel.nomeMercadoriaSaidaAtualizar);

			if (Convert.ToInt32(QntdSaidaAntiga.Rows[0].ItemArray[0]) < quantidade)
			{
				int ValorDiferenca = quantidade - Convert.ToInt32(QntdSaidaAntiga.Rows[0].ItemArray[0]);
				int novoValor = Convert.ToInt32(QntdTotalAtual.Rows[0].ItemArray[0]) - ValorDiferenca;
				DatabaseQuantidadeTotal.AtualizarQuantidade(novoValor, GetDataModel.nomeMercadoriaSaidaAtualizar);

			} else if(Convert.ToInt32(QntdSaidaAntiga.Rows[0].ItemArray[0]) > quantidade)
			{
				int ValorDiferenca = Convert.ToInt32(QntdSaidaAntiga.Rows[0].ItemArray[0]) - quantidade;
				int novoValor = Convert.ToInt32(QntdTotalAtual.Rows[0].ItemArray[0]) + ValorDiferenca;
				DatabaseQuantidadeTotal.AtualizarQuantidade(novoValor, GetDataModel.nomeMercadoriaSaidaAtualizar);
			}


			DatabaseSaida.AtualizarHistoricoSaida(GetDataModel.idAtualizarHistorico, quantidade, dia, mes, ano, hora, local);
			GetDataModel.MercadoriasEntradaHistorico = null;
			GetDataModel.MercadoriasSaidaHistorico = null;

			return RedirectToAction("Index");
		}

		// MÉTODO QUE GERA O PDF, FEITO COM iTextSharp
		public ActionResult Pdf()
		{

			Document doc = new(PageSize.A4);
			doc.SetMargins(20, 20, 30, 30);
			doc.AddCreationDate();
			string caminho = AppDomain.CurrentDomain.BaseDirectory + @"\pdf\" + "relatorio.pdf";
			_ = PdfWriter.GetInstance(doc, new FileStream(caminho, FileMode.Create));

			doc.Open();

			Paragraph titulo = new()
			{
				Font = new Font(Font.FontFamily.COURIER, 30),
				Alignment = Element.ALIGN_CENTER
			};
			titulo.Add("Relatório das Ações\n\n\n\n");
			doc.Add(titulo);

			Paragraph subtitulo1 = new()
			{
				Font = new Font(Font.FontFamily.COURIER, 20),
				Alignment = Element.ALIGN_CENTER
			};
			subtitulo1.Add("Mercadorias Entrada\n\n\n\n");
			doc.Add(subtitulo1);
			_ = new
			Paragraph()
			{
				Font = new Font(Font.FontFamily.COURIER, 20)
			};

			DataTable dadosEntrada = DatabaseEntrada.ObterDadosRelatorioEntrada();

			PdfPTable table = new(7);
			table.AddCell("N° Registro");
			table.AddCell("Mês de entrada");
			table.AddCell("Mercadoria");
			table.AddCell("Quantidade");
			table.AddCell("Hora");
			table.AddCell("Dia");
			table.AddCell("Ano");


			foreach (DataRow row in dadosEntrada.Rows)
			{
				string? mesEntrada = row["MES_ENT"].ToString();
				switch (mesEntrada)
				{
					case "1":
						mesEntrada = "Janeiro";
						break;
					case "2":
						mesEntrada = "Fevereiro";
						break;
					case "3":
						mesEntrada = "Março";
						break;
					case "4":
						mesEntrada = "Abril";
						break;
					case "5":
						mesEntrada = "Maio";
						break;
					case "6":
						mesEntrada = "Junho";
						break;
					case "7":
						mesEntrada = "Julho";
						break;
					case "8":
						mesEntrada = "Agosto";
						break;
					case "9":
						mesEntrada = "Setembro";
						break;
					case "10":
						mesEntrada = "Outubro";
						break;
					case "11":
						mesEntrada = "Novembro";
						break;
					case "12":
						mesEntrada = "Dezembro";
						break;
				}
				table.AddCell(row["ID_ENT"].ToString());
				table.AddCell(mesEntrada);
				table.AddCell(row["MERCADORIA_ENT"].ToString());
				table.AddCell(row["QUANTIDADE_ENT"].ToString());
				table.AddCell(row["HORA_ENT"].ToString() + " hrs");
				table.AddCell(row["DIA_ENT"].ToString());
				table.AddCell(row["ANO_ENT"].ToString());

			}

			doc.Add(table);

			Paragraph separador = new()
			{
				Alignment = Element.ALIGN_CENTER
			};
			separador.Add("------------------------------------------------\n\n\n\n");
			doc.Add(separador);

			Paragraph subtitulo2 = new()
			{
				Font = new Font(Font.FontFamily.COURIER, 20),
				Alignment = Element.ALIGN_CENTER
			};
			subtitulo2.Add("Mercadorias Saída\n\n\n\n");
			doc.Add(subtitulo2);

			DataTable dadosSaida = DatabaseSaida.ObterDadosRelatorioSaida();

			PdfPTable table2 = new(7);
			table2.AddCell("N° Registro");
			table2.AddCell("Mês de saída");
			table2.AddCell("Mercadoria");
			table2.AddCell("Quantidade");
			table2.AddCell("Hora");
			table2.AddCell("Dia");
			table2.AddCell("Ano");


			foreach (DataRow row in dadosSaida.Rows)
			{

				string? mesSaida = row["MES_SAIDA"].ToString();
				switch (mesSaida)
				{

Views/Historico/AttHistoricoEntrada.cshtml
@using System.Data;
@using System.Web;
@{
    ViewData["Title"] = "Atualizar registro";

}

@foreach(DataRow row in GetDataModel.DadosHistoricoEntAtt.Rows)
{
    <form id="form-entrada-att" class="w-25" method="post" action="@Url.Action("AtualizarHistoricoEnt", "Historico")">
        <div class="form-group">
            <label for="quantidade">Quantidade</label>
            <input value="@HttpUtility.HtmlDecode(row["QUANTIDADE_ENT"].ToString())" type="number" class="form-control" name="quantidade" id="quantidade-ent-att" placeholder="Quantidades de produto">
        </div>
        <div class="w-100 d-flex">
            <div>
                <label for="dia">Dia</label>
                <input value="@HttpUtility.HtmlDecode(row["DIA_ENT"].ToString())" type="number" class="form-control" name="dia" id="dia-ent-att" placeholder="Dia">
            </div>
            <div class="form-group">
                <label for="mes">Mês</label>
                <input value="@HttpUtility.HtmlDecode(row["MES_ENT"].ToString())" type="number" class="form-control" name="mes" id="mes-ent-att" placeholder="01,02,03">
            </div>
            <div class="form-group">
                <label for="ano">Ano</label>
                <input value="@HttpUtility.HtmlDecode(row["ANO_ENT"].ToString())" type="number" class="form-control" name="ano" id="ano-ent-att" placeholder="Ano">
            </div>
        </div>

        <div class="form-group">
            <label for="hora">Hora</label>
            <input value="@HttpUtility.HtmlDecode(row["HORA_ENT"].ToString())" type="text" class="form-control" name="hora" id="hora-ent-att" placeholder="HH:MM">
        </div>
        <div class="form-group">
            <label for="local">Local</label>
            <input value="@HttpUtility.HtmlDecode(row["LOCAL_ENT"].ToString())" type="text" class="form-control" name="local" id="local-ent-att" placeholder="Local">
        </div>

        <a class="btn btn-secondary" href="@Url.Action("Index")">Voltar</a>
        <button type="submit" class="btn btn-primary mt-1">Atualizar</button>
    </form>
}

Views/Historico/AttHistoricoSaida.cshtml
@using System.Data;
@using System.Web;
@{
    ViewData["Title"] = "Atualizar registro";
}

@foreach(DataRow row in GetDataModel.DadosHistoricoSaidaAtt.Rows)
{
    <form id="form-saida-att" class="w-25" method="post" action="@Url.Action("AtualizarHistoricoSaida", "Historico")">
        <div class="form-group">
            <label for="quantidade">Quantidade</label>
            <input value="@HttpUtility.HtmlDecode(row["QUANTIDADE_SAIDA"].ToString())" type="number" class="form-control" name="quantidade" id="quantidade-saida-att" placeholder="Quantidades de produto">
        </div>
        <div class="w-100 d-flex">
            <div>
                <label for="dia">Dia</label>
                <input value="@HttpUtility.HtmlDecode(row["DIA_SAIDA"].ToString())" type="number" class="form-control" name="dia" id="dia-saida-att" placeholder="Dia">
            </div>
            <div class="form-group">
                <label for="mes">Mês</label>
                <input value="@HttpUtility.HtmlDecode(row["MES_SAIDA"].ToString())" type="number" class="form-control" name="mes" id="mes-saida-att" placeholder="01,02,03">
            </div>
            <div class="form-group">
                <label for="ano">Ano</label>
                <input value="@HttpUtility.HtmlDecode(row["ANO_SAIDA"].ToString())" type="number" class="form-control" name="ano" id="ano-saida-att" placeholder="Ano">
            </div>
        </div>
        <div class="form-group">
            <label for="hora">Hora</label>
            <input value="@HttpUtility.HtmlDecode(row["HORA_SAIDA"].ToString())" type="text" class="form-control" name="hora" id="hora-saida-att" placeholder="HH:MM">
        </div>
        <div class="form-group">
            <label for="local">Local</label>
            <input value="@HttpUtility.HtmlDecode(row["LOCAL_SAIDA"].ToString())" type="text" class="form-control" name="local" id="local-saida-att" placeholder="Local">
        </div>

        <a class="btn btn-secondary" href="@Url.Action("Index")">Voltar</a>
        <button type="submit" class="btn btn-primary mt-1">Atualizar</button>
    </form>
}

Views/Historico/ConfirmarExcSaida.cshtml
@{
    ViewData["Title"] = "Confirmar exclusão";
}

<h1 class="display-4 text-secondary">Confirma excluir esse histórico de saída?</h1>

<form action="@Url.Action("HistoricoSaidaExc", "Historico")">
    <button class="btn btn-outline-primary w-25">Confirmar</button>
</form>
<form action="@Url.Action("Index", "Historico")">
    <button class="btn btn-outline-danger w-25 mt-1">Cancelar</button>
</form>

Views/Historico/HistoricoConfirmarExc.cshtml
@{
    ViewData["Title"] = "Confirmar exclusão";
}

<h1 class="display-4 text-secondary">Confirma excluir esse histórico de entrada?</h1>

<form action="@Url.Action("ExcHistoricoEnt", "Historico")">
    <button class="btn btn-outline-primary w-25">Confirmar</button>
</form>
<form action="@Url.Action("Index", "Historico")">
    <button class="btn btn-outline-danger w-25 mt-1">Cancelar</button>
</form>

Views/Historico/Index.cshtml
@using System.Data;
@using processo_estágio.BancoDeDados.Entrada;
@model GetDataModel
@{
    ViewData["Title"] = "Histórico dos produtos";

}


	<div class="mb-5">
		<h1 class="text-secondary display-4">Histórico de Entrada</h1>
		<form method="get" action="Historico/ObterDadosEntrada">
			<div class="w-50 d-flex">
				<select name="mercadoria" class="form-select w-50 mt-5 mb-5">
					@foreach (DataRow row in Model.MercadoriasModel.Rows)
					{
						<option value=@row["NOME"]>@row["NOME"]</option>
					}
				</select>
			</div>
			<button class="btn btn-secondary w-25 mb-5">Pesquisar</button>
		</form>
		<table class="table table-primary w-100">
			<thead>
				<tr class="table-primary">
					<th class="table-primary">N° Registro</th>
					<th class="table-primary">Quantidade Entrada</th>
					<th class="table-primary">Dia</th>
					<th class="table-primary">Mês</th>
					<th class="table-primary">Ano</th>
					<th class="table-primary">Hora</th>
					<th class="table-primary">Local</th>
					<th class="table-primary">Mercadoria</th>
					<th class="table-primary"></th>
				</tr>
			</thead>
			<tbody>
				@if (GetDataModel.MercadoriasEntradaHistorico != null)
				{
					if (GetDataModel.MercadoriasEntradaHistorico.Rows.Count > 0)
					{
						@foreach (DataRow row in GetDataModel.MercadoriasEntradaHistorico.Rows)
						{
							<tr>
								@foreach (var cell in row.ItemArray)
								{
									<td>@cell</td>
								}
								<td>
								<a class="btn btn-outline-primary" href="@Url.Action("AttHistoricoEntrada", new { id = row["ID_ENT"], nome = row["MERCADORIA_ENT"]})">Editar</a>
								<a class="btn btn-outline-danger" href="@Url.Action("HistoricoConfirmarExc", new { id = row["ID_ENT"], nome = row["MERCADORIA_ENT"]})">Deletar</a>
								</td>
							</tr>
						}
					}
					else
					{
						<p>Sem movimentações de entrada desse produto.</p>
					}
				}
			</tbody>
		</table>
	</div>

<div class="mb-5">
		<h1 class="text-secondary display-4">Histórico de Saída</h1>
		<form method="get" action="Historico/ObterDadosSaidaSegundo">
			<div class="w-50 d-flex">
				<select name="mercadoria" class="form-select w-50 mt-5 mb-5">
					@foreach (DataRow row in Model.MercadoriasModel.Rows)
					{
						<option value=@row["NOME"]>@row["NOME"]</option>
					}
				</select>
			</div>
			<button class="btn btn-secondary w-25 mb-5">Pesquisar</button>
		</form>
		<table class="table table-primary w-100">
			<thead>
				<tr class="table-primary">
					<th class="table-primary">N° Registro</th>
					<th class="table-primary">Quantidade Saída</th>
					<th class="table-primary">Dia</th>
					<th class="table-primary">Mês</th>
					<th class="table-primary">Ano</th>
					<th class="table-primary">Hora</th>
					<th class="table-primary">Local</th>
					<th class="table-primary">Mercadoria</th>
					<th class="table-primary"></th>
				</tr>
			</thead>
			<tbody>
				@if (GetDataModel.MercadoriasSaidaHistorico != null)
				{
					if (GetDataModel.MercadoriasSaidaHistorico.Rows.Count > 0)
					{
						@foreach (DataRow row in GetDataModel.MercadoriasSaidaHistorico.Rows)
						{
							<tr>
								@foreach (var cell in row.ItemArray)
								{
									<td>@cell</td>
								}
							<td>
								@*href="Historico/AttHistoricoSaida/@row["ID_SAIDA"]"*@
								<a class="btn btn-outline-primary" href="@Url.Action("AttHistoricoSaida", new {id = row["ID_SAIDA"], nome = row["MERCADORIA_SAIDA"]} )">Editar</a>
								<a class="btn btn-outline-danger" href="@Url.Action("ConfirmarExcSaida", new { id = row["ID_SAIDA"], quantidade = row["QUANTIDADE_SAIDA"], nome = row["MERCADORIA_SAIDA"]})">Deletar</a>
							</td>
							</tr>
						}
					}
					else
					{
						<p>Sem movimentações de saída desse produto.</p>
					}
				}
			</tbody>
		</table>
	</div>


<a class="btn btn-danger mt-5" href="@Url.Action("Pdf")">Gerar relatório</a>